#' Function to filter the transcriptome based on occupancy
#' The occupancy criteria testet are  90%, 70%, 50%
#'
#'
#' @param df Transcriptomics matrix
#' @param sampledata sample information dataframe
#' @param comp which comparison
#'
#' @export
conditional_filt <- function(df, sampledata,  comp){
  sample_data <-
    sampledata |>
    dplyr::mutate(comparison = case_when(grepl('^A375',samplegroup) ~ "A375",
                                         grepl('^WM47',samplegroup) ~ "WM47",
                                         grepl('^WM3311',samplegroup) ~ "WM3311",
                                         grepl('^WM3000',samplegroup) ~ "WM3000")) |>
    dplyr::mutate(condition = case_when(grepl('CTRL',samplegroup) ~ "Control",
                                        grepl('LCT', samplegroup) ~ "LCT")) |>
    dplyr::mutate(id = sampleID) |>
    dplyr::select(id, samplegroup, condition,-sampleID, everything())

  sample_data_filt<- sample_data |> dplyr::filter(comparison == comp)  #"A375"
  Control_col <- as.vector(sample_data_filt[sample_data_filt$condition == "Control", "id"]$id)
  Exp_col <-  as.vector(sample_data_filt[sample_data_filt$condition == "LCT", "id"]$id)

  dt <- df |>
    dplyr::select(all_of(c("GeneType", "GeneSymbol","ENSG", Control_col, Exp_col)))

  perc90ctrl <- dt %>%  dplyr::filter(rowMeans(.[, Control_col] != 0) >= 0.9)
  perc90lct <- dt %>%  dplyr::filter(rowMeans(.[, Exp_col] != 0) > 0.9)

  perc70ctrl <- dt %>%  dplyr::filter(rowMeans(.[, Control_col] != 0) >= 0.7)
  perc70lct <- dt %>%  dplyr::filter(rowMeans(.[, Exp_col] != 0) > 0.7)

  perc50ctrl <- dt %>%  dplyr::filter(rowMeans(.[, Control_col] != 0) >= 0.5)
  perc50lct <- dt %>%  dplyr::filter(rowMeans(.[, Exp_col] != 0) > 0.5)

  # Return dataframe names and dimensions
  return(list(comp,
              dim(perc90ctrl)[1], dim(perc90lct)[1],
              dim(perc70ctrl)[1], dim(perc70lct)[1],
              dim(perc50ctrl)[1], dim(perc50lct)[1],
              perc90ctrl, perc90lct,
              perc70ctrl, perc70lct,
              perc50ctrl, perc50lct,  dt ))
}

#' Separate metabolome data by cell line
#'
#' Uses transcriptome sample metadata to subset metabolomics data.
#'
#' @param transcript_data Transcriptomics matrix
#' @param metabolome_data Metabolomics matrix
#' @param write_file Output CSV file
#'
#' @export
save_separate_cell_lines <- function(transcript_data, metabolome_data, write_file){
  # We take transcriptome data just for sample info
  # Transcriptome is separates by xenograft in previous step
  columns <- names(transcript_data)[-c(1,2,3)]
  metab_df <- metabolome_data |> t() |> as.data.frame() |>
    dplyr::select(all_of(columns)) |> t() |> as.data.frame() |>
    rownames_to_column("sampleID") |> left_join(sample_sub) |>
    dplyr::select( sampleID, samplegroup, everything(), -sampleName)
  write.table(metab_df , file = write_file, sep=",", row.names=FALSE)
}


#' Add log fold change to the metaboanalyst t-test results
#'
#' Uses transcriptome sample metadata to subset metabolomics data.
#'
#' @param raw_file raw file submitted to metaboanalyst (generated by save_separate_cell_lines)
#' @param metabolome_data metaboanalyst t-test result object
#'
#' @export
add_log2FC <- function(raw_file, t_res) {
  raw_metabolome <- read.csv(raw_file)
  mean_intensities <- raw_metabolome %>%
    pivot_longer(cols = -c(sampleID, samplegroup),
                 names_to = "Metabolite", values_to = "Intensity") %>%
    group_by(Metabolite, samplegroup) %>%
    summarise(Mean_Intensity = mean(Intensity, na.rm = TRUE)) %>%
    pivot_wider(names_from = samplegroup, values_from = Mean_Intensity)
  # Compute log2 fold change
  mean_intensities$log2FC <- log2(mean_intensities[[3]]/mean_intensities[[2]])
  t_res[["analSet"]][["logFC"]] <- mean_intensities
  # return results
  return(t_res)
}

#' Run correlation analysis
#'
#' Uses transcriptome sample metadata to subset metabolomics data.
#'
#' @param transcript_data filtered/tpm-scaled transcriptome
#' @param metabolome_data complete metabolome
#' @param selected_metabolite selected metabolites vector (significant results from t-test)
#'
#' @export
run_selected_correlation <-
  function(transcript_data, metabolome_data, selected_metabolite){
    # Remove special characters from both
    #  1. selected_metabolite
    #  2. column names of metabolome_data
    metab_of_interest <- gsub("_", ".", selected_metabolite)
    clean_names <-
      mgsub(names(metabolome_data),
            pattern = c("\\(", ")", " ", "/", ":","-", "_"),
            replacement = c(".", ".", ".", ".",".",".", "."))
    new_clean_names <-
      ifelse(str_detect(clean_names, "^[0-9]"), paste0("X", clean_names), clean_names)
    names(metabolome_data) <- new_clean_names
    # Set column order
    transcript_data <-
      transcript_data |> dplyr::select(GeneType, GeneSymbol, ENSG, everything())
    columns <- names(transcript_data)[-c(1,2, 3)]
    metab_df <-
      metabolome_data |>
      dplyr::select(all_of(metab_of_interest)) |> t() |>
      as.data.frame() |>
      dplyr::select(all_of(columns)) |>
      t() |> as.data.frame()

    genes_df <-
      transcript_data |>
      column_to_rownames("ENSG") |>
      dplyr::select(-GeneType, -GeneSymbol) |>
      t() |> as.data.frame()

    # Compute correlations and slopes
    cor_results <-
      expand.grid(Gene = colnames(genes_df), Metabolite = colnames(metab_df)) %>%
      rowwise() %>% mutate(
        cor_test = list(cor.test(genes_df[[Gene]], metab_df[[Metabolite]], method = "pearson")),
        cor = cor_test$estimate,     # Extract correlation coefficient
        p_value = cor_test$p.value,  # Extract p-value
        slope = coef(lm(metab_df[[Metabolite]] ~ genes_df[[Gene]]))[2]  # slope from linear model
      ) %>% ungroup() %>%
      arrange(desc(abs(cor)), desc(abs(slope)))  # Rank by absolute correlation and slope
    return(as.data.frame(cor_results))

  }


#' Run correlation analysis with fdr added (FDR is not actually needed here)
#'
#' Uses transcriptome sample metadata to subset metabolomics data.
#'
#' @param transcript_data filtered/tpm-scaled transcriptome
#' @param metabolome_data complete metabolome
#' @param selected_metabolite selected metabolites vector (significant results from t-test)
#'
run_selected_correlation_fdr <-
  function(transcript_data, metabolome_data, selected_metabolite){

    # Clean metabolite name
    metab_of_interest <- gsub("_", ".", selected_metabolite)

    clean_names <-
      mgsub(
        names(metabolome_data),
        pattern = c("\\(", ")", " ", "/", ":", "-", "_"),
        replacement = c(".", ".", ".", ".", ".", ".", ".")
      )

    new_clean_names <-
      ifelse(str_detect(clean_names, "^[0-9]"),
             paste0("X", clean_names),
             clean_names)

    names(metabolome_data) <- new_clean_names

    # Order transcript columns
    transcript_data <-
      transcript_data |> dplyr::select(GeneType, GeneSymbol, ENSG, everything())

    columns <- names(transcript_data)[-c(1, 2, 3)]

    metab_df <-
      metabolome_data |>
      dplyr::select(all_of(metab_of_interest)) |>
      t() |>
      as.data.frame() |>
      dplyr::select(all_of(columns)) |>
      t() |>
      as.data.frame()

    genes_df <-
      transcript_data |>
      column_to_rownames("ENSG") |>
      dplyr::select(-GeneType, -GeneSymbol) |>
      t() |>
      as.data.frame()

    # Correlation + slope
    cor_results <-
      expand.grid(
        Gene = colnames(genes_df),
        Metabolite = colnames(metab_df),
        stringsAsFactors = FALSE
      ) |>
      rowwise() |>
      mutate(
        cor_test = list(
          cor.test(
            genes_df[[Gene]],
            metab_df[[Metabolite]],
            method = "pearson"
          )
        ),
        cor     = unname(cor_test$estimate),
        p_value = cor_test$p.value,
        slope   = coef(lm(metab_df[[Metabolite]] ~ genes_df[[Gene]]))[2]
      ) |>
      ungroup() |>
      mutate(
        FDR = p.adjust(p_value, method = "BH")
      ) |>
      arrange(desc(abs(cor)), desc(abs(slope)))

    return(as.data.frame(cor_results))
  }


#' Information about the mapping of metabolites/lipids from kit to HMDB
#' This is to know the percentage of metabolites/lipids having corresponding HMDB ids
#'
#'
#' @param dataframe (curated data by Daniela and Rudy)
#' @export
get_mapping_info <- function(dataframe){
  df <-
    dataframe |>
    #dplyr::mutate(ENSG = Gene ) |>
    dplyr::left_join(rudy_dani_hmdb) |>
    dplyr::left_join(gene_ensembl)
  non_lipids_df <-
    df |>
    dplyr::filter(abs(cor) >=0.7, abs(slope)>=1, source =="non_lipids") |>
    dplyr::select(GeneSymbol, cor, Metabolite, HMDB, Name)
  non_lipids_multiple_hmdbs <-
    non_lipids_df %>%
    dplyr::group_by(Name) %>%
    summarize(n_ids = n_distinct(HMDB)) %>%
    filter(n_ids > 1) %>%
    tally(name = "n_metabolites_with_multiple_ids")

  non_lipids_id_mapping_perc <-
    round(((length(unique(non_lipids_df$HMDB)  |> na.exclude()) - non_lipids_multiple_hmdbs$n_metabolites_with_multiple_ids[[1]])/
             length(unique(non_lipids_df$Name))) *100,2)

  ipids_df <- df |>
    dplyr::filter(abs(cor) >=0.7, abs(slope)>=1, source =="lipids") |>
    dplyr::select(GeneSymbol, cor, Metabolite, HMDB, Name)

  lipids_multiple_hmdbs<-
    ipids_df %>%
    dplyr::group_by(Name) %>%
    summarize(n_ids = n_distinct(HMDB)) %>%
    filter(n_ids > 1) %>%
    tally(name = "n_metabolites_with_multiple_ids")
  lipids_id_mapping_perc <-
    round(((length(unique(ipids_df$HMDB)  |> na.exclude()) - lipids_multiple_hmdbs$n_metabolites_with_multiple_ids[[1]])/
             length(unique(ipids_df$Name))) *100,2)

  return(list(non_lipids_df, non_lipids_id_mapping_perc,
              ipids_df, lipids_id_mapping_perc))
}


#' Process the results
#'
#' As metabolites are column names, R adds X in front of the columns that start with numbers
#' In order to match metabolite names with annotations we need to handle these cases long with
#' some other cases
#'
#' @param dataframe raw file submitted to metaboanalyst (generated by save_separate_cell_lines)
#' @export
process_results <- function(dataframe){
  dataframe$Metabolite<- trimws(dataframe$Metabolite)
  dataframe$Metabolite[dataframe$Metabolite == 'X3.Met.His'] <- '3.Met.His'
  dataframe$Metabolite[dataframe$Metabolite == 'X1.Met.His'] <- '1.Met.His'
  dataframe$Metabolite[dataframe$Metabolite == 'X5.AVA'] <- '5.AVA'
  dataframe$Metabolite[dataframe$Metabolite == 'C4.OH'] <- 'C3-DC (C4-OH)'
  dataframe$Metabolite[dataframe$Metabolite == 'C6.OH'] <- 'C5-DC (C6-OH)'
  dataframe$Metabolite[dataframe$Metabolite == 'C12.OH'] <- 'C12-DC'
  dataframe$norm_metab <- normalize_name(dataframe$Metabolite)
  return(dataframe)
}

#' Process metaboAnalyst joint Pathway analysis results
#'
#' It takes gene/metabolite accession and pings KEGG to get common name and
#' returns the updated table
#'
#' @param metaboanalyst_results MetaboAnalyst results with all the statistics
#' @param metabolome_data MetaboAnalyst mapping file with pathway name and accessions of genes and metabolites
#'
#'
#' @export
process_metaboanalyst <- function(
    metaboanalyst_results,
    metaboanalyst_mapping){
  n <- nrow(metaboanalyst_mapping)
  # Process bar from utils
  pb <- txtProgressBar(min = 0, max = n, style = 3)
  resolved_names <- character(n)
  for (i in seq_len(n)) {
    kegg_str <- metaboanalyst_mapping$matched_features[i]
    resolved_names[i] <- resolve_kegg_ids(kegg_str)
    setTxtProgressBar(pb, i)
  }
  close(pb)
  metaboanalyst_mapping$names <- resolved_names
  res_map <-
    left_join(metaboanalyst_mapping,
              metaboanalyst_results) |>
    rowwise() %>%
    mutate(
      feature_list = str_split(matched_features, ";\\s*"),
      n_cpd = sum(str_detect(feature_list, "^cpd:")),
      n_hsa = sum(str_detect(feature_list, "^hsa:")),
      total = length(feature_list)
    ) %>% ungroup() %>% dplyr::select(-feature_list)
  return(res_map)
}

#' Count contribution of genes and metabolites in pathway
#'
#' It takes the metaboAnalyst results and decides contribution of genes and metabolites
#' contributing the pathways and returns the updated table
#'
#' @param metaboanalyst_results MetaboAnalyst results with all the statistics
#' @param metabolome_data MetaboAnalyst mapping file with pathway name and accessions of genes and metabolites
#'
#'
#' @export
count_contrib <- function(df){
  df <- df |> rowwise() %>%
    dplyr::mutate(
      features = str_split(matched_features, ";\\s*"),
      n_metab = sum(str_detect(features, "^cpd:")),
      n_gene = sum(str_detect(features, "^hsa:")),
      total = n_metab + n_gene,
      type = case_when(
        total == 0 ~ NA_character_,
        n_metab / total >= 0.99 ~ "metabolites based",
        n_gene / total >= 0.99 ~ "genes based",
        TRUE ~ "mixed"
      )
    ) %>%
    ungroup() %>%
    dplyr::select(-features, n_metab, n_gene, total)
  df
}

#' Count contribution of genes and metabolites in pathway
#'
#' It takes the metaboAnalyst results and decides contribution of genes and metabolites
#' contributing the pathways and returns the updated table
#'
#' @param pathway pathway of interest
#' @param res_map_list Result map list
#' @param title_prefix title
#'
#' @export
plot_pathway_presence_heatmap <- function(
    pathway,
    res_map_list,
    title_prefix = NULL
) {
  require(stringr)
  require(pheatmap)
  # ---------- Helper: extract features safely ----------
  extract_features <- function(df, pathway) {

    if (!"X" %in% colnames(df) || !"names" %in% colnames(df)) {
      return(character(0))}
    row <- df[df$X == pathway, "names", drop = TRUE]
    if (length(row) == 0 || is.na(row) || row == "") {
      return(character(0))}
    str_split(row, "; ")[[1]]
  }
  # ---------- Build named list of features ----------
  names_list <- lapply(res_map_list, extract_features, pathway = pathway)
  # ---------- Remove completely empty datasets ----------
  if (all(sapply(names_list, length) == 0)) {
    stop("Pathway not found in any dataset: ", pathway)}
  # ---------- Union of all features ----------
  all_features <- sort(unique(unlist(names_list)))
  if (length(all_features) == 0) {
    stop("No features found for pathway: ", pathway)}
  # ---------- Presence / absence matrix ----------
  heatmat <- sapply(names_list, function(x) {
    as.integer(all_features %in% x)})
  rownames(heatmat) <- all_features
  # ---------- Title ----------
  main_title <- if (is.null(title_prefix)) {
    paste0(pathway, "\nFeature presence across xenografts")
  } else {
    paste0(title_prefix, "\n", pathway)
  }
  # ---------- Heatmap ----------
  pheatmap(
    heatmat,
    color = c("khaki", "firebrick"),
    breaks = c(-0.5, 0.5, 1.5),
    legend_breaks = c(0, 1),
    legend_labels = c("Absent", "Present"),
    cluster_rows = TRUE,
    cluster_cols = FALSE,
    border_color = "grey80",
    fontsize_row = 8,
    fontsize_col = 12,
    main = main_title
  )
}


#' Plot combined KEGG pathway
#' highlighting the genes and metabolites that were queried for pathway enrichment
#'
#'
#' @param pathway_name Pathway name
#' @param pathway_id KEGG pathway accession
#' @param res_map_list genes and metabolites to highlight
#'
#' @export
plot_combined_kegg_pathway <- function(
    pathway_name,
    pathway_id,
    res_map_list,
    species = "hsa",
    file.type = "png",
    out.prefix = NULL
) {
  require(stringr)
  require(pathview)
  # ---------- extract features ----------
  extract_from_df <- function(df) {
    if (!all(c("X", "matched_features") %in% colnames(df))) {
      return(character(0))
    }

    row <- df[df$X == pathway_name, "matched_features", drop = TRUE]

    if (length(row) == 0 || is.na(row) || row == "") {
      return(character(0))
    }

    str_split(row, ";\\s*")[[1]]
  }

  all_kegg_ids <- unique(unlist(lapply(res_map_list, extract_from_df)))

  if (length(all_kegg_ids) == 0) {
    stop("No matched KEGG features found for pathway: ", pathway_name)
  }

  # ---------- split genes / compounds ----------
  genes <- sub("^hsa:", "", all_kegg_ids[grepl("^hsa:", all_kegg_ids)])
  cpds  <- sub("^cpd:", "", all_kegg_ids[grepl("^cpd:", all_kegg_ids)])

  gene_vec <- if (length(genes) > 0) setNames(rep(1, length(genes)), genes) else NULL
  cpd_vec  <- if (length(cpds)  > 0) setNames(rep(1, length(cpds)),  cpds)  else NULL

  # ---------- output naming ----------
  if (is.null(out.prefix)) {
    out.prefix <- gsub("\\s+", "_", pathway_name)
  }

  # ---------- draw pathway ----------
  pv <- pathview(
    gene.data   = gene_vec,
    cpd.data    = cpd_vec,
    pathway.id  = pathway_id,
    species     = species,
    kegg.native = TRUE,
    file.type   = file.type,
    out.suffix  = paste0(out.prefix, "_combined")
  )

  invisible(pv)
}



#' Add additional column in the MetaboAnalyst results
#' Where any of the mapped genes in the DEGs
#'
#' @export
add_overlapping_genes <- function(df,
                                  deg_universe,
                                  gene_col = "names",
                                  new_col  = "overlapping_DEGs",
                                  na_if_empty = TRUE) {
  require(stringr)

  if (!gene_col %in% colnames(df)) {
    stop("Column ", gene_col, " not found in data frame")
  }

  df[[new_col]] <- vapply(df[[gene_col]], function(gene_string) {
    if (is.na(gene_string) || gene_string == "") {
      return(if (na_if_empty) NA_character_ else "")
    }
    genes <- str_split(gene_string, ";\\s*")[[1]]
    overlap <- intersect(genes, deg_universe)
    if (length(overlap) == 0) {
      if (na_if_empty) NA_character_ else ""
    } else {
      paste(overlap, collapse = "; ")
    }

  }, character(1))

  df
}


#' Separate metabolome and transcriptome data by cell line to be
#' analysed by mixOmics
#' Uses transcriptome sample metadata to subset metabolomics data.
#'
#' @param transc_df Transcriptomics matrix
#' @param metab_mat Metabolomics matrix
#' @param meta metadata dataframe
#' @param comp Comparison of interest
#'
#' @export
create_mixOmics_input <- function(metab_mat, transc_df, meta, comp){
  mixomics_list <- list()

  sample_data <-  sampledata |>  #meta |>
    dplyr::mutate(comparison = case_when(
      grepl('^A375',samplegroup) ~ "A375",
      grepl('^WM47',samplegroup) ~ "WM47",
      grepl('^WM3311',samplegroup) ~ "WM3311",
      grepl('^WM3000',samplegroup) ~ "WM3000")) |>
    dplyr::rename("id" = sampleID) |> dplyr::select(id, samplegroup, everything())

  sample_data_filt<- sample_data |> dplyr::filter(comparison == comp)

  mixomics_list[["sample_meta"]] <- sample_data_filt

  mixomics_list[["metab_sel"]] <-
    t(metab_mat) |> as.data.frame() |>
    dplyr::select(all_of(sample_data_filt$id)) |>
    as.matrix() |> t()

  mixomics_list[["transc_sel"]] <-
    transc_df %>%
    mutate(ENSG = sub("\\.\\d+$", "", ENSG)) %>%
    # Count non-zero values across sample columns
    rowwise() %>%
    mutate(non_zero_count = sum(c_across(starts_with("DW")) != 0)) %>%
    ungroup() %>%
    # For each geneSymbol, keep the row with most non-zero values
    group_by(GeneSymbol) %>%
    slice_max(order_by = non_zero_count, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    dplyr::select(-non_zero_count, -GeneType, -ENSG) %>%
    column_to_rownames(var = "GeneSymbol") %>% t()
  return(mixomics_list)
}

library(RaMP)

#' Given a list of metabolites short names
#' pull hmdb ids from annotation dataframe
#' Annotation dataframe created by Rudy and Daniela
#'
#' @param metab_list metabolite short name list
#' @param type whether metabolite list consist of "lipid" or "non-lipid" or
#' "none" in case we want all of them
#' @export
get_hmdb_ids <- function(metab_list, type){
  if (type != "none") {
    hmdb_column <-
      rudy_dani_hmdb |>
      dplyr::filter(source == type) |>
      dplyr::select(HMDB, Name, Short.Name, Associated_genes) |>
      dplyr::filter(Short.Name %in% metab_list) |>
      drop_na() |>
      dplyr::pull(HMDB) |>
      unique()
    return(hmdb_column)
  } else {
    hmdb_column <-
      rudy_dani_hmdb |>
      dplyr::select(HMDB, Name, Short.Name, Associated_genes) |>
      dplyr::filter(Short.Name %in% metab_list) |>
      drop_na() |>
      dplyr::pull(HMDB) |>
      unique()
    return(hmdb_column)
  }
}

# rampDB <- RaMP()
#' RaMP DB is not usable for this version of R/bioconductor
getEnrichment <- function(metabolites){
  metab_paste <- c()
  for (i in get_hmdb_ids(metabolites, "none")){
    metab_paste <- c(metab_paste, paste0("hmdb:",i))}
  pathwaydfids <-
    getPathwayFromAnalyte(db = rampDB, metab_paste, include_smpdb = TRUE)
  fisher.results <- runCombinedFisherTest(db = rampDB, analytes = metab_paste)
  filtered.fisher.results <-
    FilterFishersResults(fisher.results, pval_type = 'holm', pval_cutoff=0.05)
  clusters <-
    RaMP::findCluster(db = rampDB, filtered.fisher.results,
                      perc_analyte_overlap = 0.2,
                      min_pathway_tocluster = 2, perc_pathway_overlap = 0.2)
  # datatable(clusters$fishresults %>% mutate_if(is.numeric, ~ round(., 8)),
  #           rownames = FALSE)
  return(clusters)
}


make_boxplot_transcriptome_pathway <-
  function(gene_vector, transcriptome, sample_metadata, title){

    require(dplyr)
    require(tidyr)
    require(ggplot2)

    pathway_genes <- intersect(gene_vector, rownames(transcriptome))

    if (length(pathway_genes) == 0) {
      stop("No genes from gene_vector found in transcriptome rownames")
    }

    expr_mat <- transcriptome
    sample_metadata <- sample_metadata[,c("sampleID", "newsample")]
    names(sample_metadata) <- c("Sample", "Group")
    meta <- sample_metadata

    expr_pathway <- expr_mat[pathway_genes, , drop = FALSE]

    expr_long <- expr_pathway |>
      as.data.frame() |>
      tibble::rownames_to_column("Gene") |>
      pivot_longer(
        cols = -Gene,
        names_to = "Sample",
        values_to = "Expression"
      )

    expr_long <- expr_long |>
      left_join(meta, by = "Sample")

    expr_long <- expr_long |>
      group_by(Gene) |>
      mutate(Expression_z = scale(Expression)[,1]) |>
      ungroup()


    pathway_boxplot <-
      ggplot(expr_long, aes(x = Group, y = Expression, fill = Group)) +
      geom_boxplot(outlier.shape = NA, alpha = 0.7) +
      geom_jitter(width = 0.15, alpha = 0.4, size = 1) +
      labs(
        title = title,
        subtitle = paste0(
          "Transcriptomic expression of ", length(pathway_genes),
          " pathway genes (metabolites excluded)" ),
        y = "Expression", x = "" ) +
      scale_fill_manual(values = c(
        A375_KD   = "red3",     A375_SD   = "pink",
        WM3000_KD = "darkblue", WM3000_SD = "lightblue",
        WM3311_KD = "darkgreen",WM3311_SD = "lightgreen",
        WM47_KD   = "orangered",WM47_SD   = "orange"
      )) +
      theme_paper(base_size = 14) +
      theme(legend.position = "none") +
      coord_flip()
    pathway_boxplot
  }

get_pathway_vector <- function(pathway_dataframe, pathway){
  goi <-
    pathway_dataframe %>%
    dplyr::filter(X == pathway) %>%
    pull(names) %>%
    noquote() %>%
    str_split(., "; ") %>%
    noquote() %>%
    as.vector()
  goi[[1]]
}


#' get the summary of correlation results
#'
#' @param corr_df Correlation results
#' @param top_n summary of top n results sorted by correlation coefficient
#' @param p_cutoff p-value cutoff currently set to 0.05
#' @param cor_cutoff cor_cutoff cutoff currently set to 0.7 positive or negative
#' @param slope_cutoff slope_cutoff cutoff currently set to 1 positive or negative
#'
#' @export
summarize_corr <- function(corr_df, top_n = 100,
                           p_cutoff = 0.05, cor_cutoff = 0.7, slope_cutoff = 1) {
  setDT(corr_df)

  # Filter significant pairs
  filtered <- corr_df %>%
    filter(p_value < p_cutoff,
           abs(cor) > cor_cutoff,
           abs(slope) > slope_cutoff)

  # Top N by absolute correlation
  topN <- filtered %>%
    arrange(desc(abs(cor))) %>%
    head(top_n)

  # 1. Count positive vs negative correlations
  pos_neg_summary <- topN %>%
    summarise(
      positive = sum(cor > 0),
      negative = sum(cor < 0)
    )

  # 2. Most connected metabolites
  metabolite_summary <- topN %>%
    group_by(Metabolite) %>%
    summarise(
      n_connections = n(),
      n_positive = sum(cor > 0),
      n_negative = sum(cor < 0)
    ) %>%
    arrange(desc(n_connections))

  # 3. Most connected genes
  gene_summary <- topN %>%
    group_by(GeneSymbol) %>%
    summarise(
      n_connections = n(),
      n_positive = sum(cor > 0),
      n_negative = sum(cor < 0)
    ) %>%
    arrange(desc(n_connections))

  # Return everything as a list
  return(list(
    n_total_filtered = nrow(filtered),
    pos_neg_summary = pos_neg_summary,
    top_metabolites = head(metabolite_summary, 10),
    top_genes = head(gene_summary, 10),
    top_pairs = topN
  ))
}

#' Summarize correlation
#'
#' @export
# Function to summarize correlations per xenograft
summarize_corr2 <- function(df, xenograft_name, thresholds = seq(0.7, 0.9, by = 0.01)) {
  # Ensure numeric
  df <- df %>%
    mutate(cor = as.numeric(cor),
           slope = as.numeric(slope),
           p_value = as.numeric(p_value))

  # Apply significance filter
  df <- df %>%
    filter(abs(slope) > 1, p_value < 0.05)

  # Calculate number of edges at different thresholds
  counts <- lapply(thresholds, function(th) {
    n <- sum(abs(df$cor) > th, na.rm = TRUE)
    data.frame(Xenograft = xenograft_name, Threshold = th, N_edges = n)
  }) %>%
    bind_rows()

  list(filtered = df, counts = counts)
}

combine_pvalues <- function(p) {
  chi_sq <- -2 * sum(log(p), na.rm = TRUE)
  df <- 2 * sum(!is.na(p))
  pchisq(chi_sq, df = df, lower.tail = FALSE)
}


#' get KEGG class and subclass information in order to group pathways into subclass
#' For webgestalt results
#' @param webgestalt webgestalt results
#' @param organism_prefix currently set to human "hsa"
#'
#' @export
webgestalt_kegg_class <- function(webgestalt, organism_prefix = "hsa") {
  pathway_ids <- unique(webgestalt$geneSet)
  # Function to fetch classification info for a vector of KEGG pathway IDs
  out_list <- lapply(pathway_ids, function(pid) {
    message("Fetching ", pid, " ...")
    res <- tryCatch(
      keggGet(pid)[[1]],
      error = function(e) NULL
    )
    if (is.null(res)) {
      return(tibble(
        geneSet = pid,
        kegg_name = NA_character_,
        CLASS = NA_character_
      ))
    }
    tibble(
      geneSet = pid,
      kegg_name = res$NAME %>% str_remove(" - Homo sapiens \\(human\\)$"),
      CLASS = if (!is.null(res$CLASS)) res$CLASS[[1]] else NA_character_
    )
  })
  kegg_info <- bind_rows(out_list)

  # Parse CLASS into levels
  kegg_info2 <- kegg_info |>
    mutate(
      CLASS = if_else(is.na(CLASS), "", CLASS),
      TopClass = str_split(CLASS, ";\\s*") %>% map_chr(~ .x[1] %||% NA_character_),
      SubClass = str_split(CLASS, ";\\s*") %>% map_chr(~ ifelse(length(.x) >= 2, .x[2], NA_character_))
    )

  # Join back
  webgestalt2 <- webgestalt |>
    left_join(kegg_info2, by = "geneSet")
}

#' get KEGG class and subclass information in order to group pathways into subclass
#' For MetaboAnalyst results
#' @param kegg_ids list of KEGG ids
#' @param organism_prefix currently set to human "hsa"
#'
#' @export
metaboanalyst_kegg_class <- function(kegg_ids, organism_prefix = "hsa") {
  pathway_ids <- unique(kegg_ids)
  # Function to fetch classification info for a vector of KEGG pathway IDs
  out_list <- lapply(pathway_ids, function(pid) {
    message("Fetching ", pid, " ...")
    res <- tryCatch(
      keggGet(pid)[[1]],
      error = function(e) NULL
    )
    if (is.null(res)) {
      return(tibble(
        geneSet = pid,
        kegg_name = NA_character_,
        CLASS = NA_character_
      ))
    }
    tibble(
      geneSet = pid,
      kegg_name = res$NAME %>% str_remove(" - Homo sapiens \\(human\\)$"),
      CLASS = if (!is.null(res$CLASS)) res$CLASS[[1]] else NA_character_
    )
  })
  kegg_info <- bind_rows(out_list)

  # Parse CLASS into levels
  kegg_info2 <- kegg_info |>
    mutate(
      CLASS = if_else(is.na(CLASS), "", CLASS),
      TopClass = str_split(CLASS, ";\\s*") %>% map_chr(~ .x[1] %||% NA_character_),
      SubClass = str_split(CLASS, ";\\s*") %>% map_chr(~ ifelse(length(.x) >= 2, .x[2], NA_character_))
    )

  # # Join back
  # webgestalt2 <- webgestalt |>
  #   left_join(kegg_info2, by = "geneSet")
  kegg_info2
}

#' get KEGG class and subclass information in order to group pathways into subclass
#' For MetaboAnalyst results
#' @param mA_results metaboAnalyst results
#' @param all_kegg_hsa all kegg export
#' @param xeno Xenograft of interest
#' @param organism_prefix currently set to human "hsa"
#'
#' @export
add_kegg_subclass_metaboanalyst <- function(mA_results , all_kegg_hsa, xeno){
  require(fuzzyjoin)
  require(KEGGREST)
  require(tidyverse)
  joint_metab_clean <- mA_results |>
    mutate(
      pathway_name_query = X,
      pathway_name_clean = str_to_lower(str_replace_all(X, "[^A-Za-z0-9]", ""))
    )
  matched <- stringdist_left_join(
    joint_metab_clean, all_hsa,
    by = "pathway_name_clean",
    max_dist = 20, # adjust tolerance; 3–5 is good
    distance_col = "dist"
  )
  matched_class <- metaboanalyst_kegg_class(matched$pathway_id, "hsa")
  joint_metab_clean_with_subclass <-
    joint_metab_clean |>
    dplyr::mutate(kegg_name = X) |>
    left_join(matched_class)
  joint_metab_clean_with_subclass$Xenograft <-  xeno
  #
  # joint_metab_clean_combined_subclass <-
  # joint_metab_clean |>
  # dplyr::mutate(kegg_name = X) |>
  # left_join(matched_class) |>
  # group_by(SubClass) |>
  # summarise(
  #   combined_p = combine_pvalues(Raw.p),
  #   combined_FDR = p.adjust(combined_p, method = "BH"),
  #   avg_Impact = mean(Impact, na.rm = TRUE)
  # ) |> arrange(combined_FDR)
  # joint_metab_clean_combined_subclass$Xenograft <-  xeno
  joint_metab_clean_with_subclass
}


#' Webgestalt results give a link to view pathways where the metabolites and gene are highlighted
#' That same link can be used to get metabolite names from ChEBI database
#' For MetaboAnalyst results
#' @param link webgestalt link
#' @param ref_df dataframe
#'
#' @export
extract_link_entities <- function(link, ref_df) {
  # 1. Extract gene names (all-caps words like IL1A, HIF1A, VEGFA)
  gene_matches <- stringr::str_extract_all(link, "(?<==)[A-Z0-9]+(?=,|&|$)")[[1]]

  # 2. Extract ChEBI IDs (ChEBI_12345 or CHEBI:12345)
  chebi_matches <- stringr::str_extract_all(link, "(?<=ChEBI_)[0-9]+|(?<=CHEBI:)[0-9]+")[[1]]
  chebi_matches <- unique(na.omit(chebi_matches))
  print(chebi_matches)

  # 3. Lookup metabolite names
  ref_df$CHEBI <- as.character(ref_df$CHEBI)
  found <- dplyr::filter(ref_df, CHEBI %in% chebi_matches)

  # 4. Create a mapping: ChEBI ID → metabolite name
  met_map <- setNames(found$`Short.Name`, found$CHEBI)

  # 5. Combine gene names + metabolites (preserving order in link)
  # Build a single ordered vector of both types
  all_matches <- stringr::str_extract_all(
    link,
    "(?<=,|=)[A-Z0-9]+(?=,|&|$)|ChEBI_[0-9]+|CHEBI:[0-9]+"
  )[[1]]

  # Replace ChEBI IDs with names if available
  all_named <- sapply(all_matches, function(x) {
    # Normalize ChEBI ID formats
    id <- sub("ChEBI_|CHEBI:", "", x)
    if (id %in% names(met_map)) {
      return(met_map[id])
    } else {
      return(x)  # likely a gene name
    }
  })

  return(all_named)
}


#df$entities <- sapply(df$link, extract_link_entities, ref_df = ref_df)
#log_WM47$entities <- sapply(log_WM47$link, extract_link_entities, ref_df = rudy_dani_hmdb)
#log_A375$entities <- sapply(log_A375$link, extract_link_entities, ref_df = rudy_dani_hmdb)


